### ISSUE TITLE
Create Modal for Homepage

### ISSUE THREAD

**Issue by kaylima** [INN/umbrella-rivard-report#9]
ESTIMATE: 8-12 hours

1. Go to http://rrlargo.staging.wpengine.com/

EXPECT: Add modal email signup to homepage

Use http://www.civilbeat.org/ as the model for this. It needs to be implemented so that Rivard can customize the pop-up's messaging and behavior.

<img width="1596" alt="civilbeat" src="https://user-images.githubusercontent.com/15877728/29080709-beff4b8c-7c1d-11e7-862e-678205aec261.png">

**Comment by benlk** [comment]
Goals: 

- Reusability: as ~partials~ as a widget
- Configurable text: as a Wordpress widget
- Configurable popup behavior: *What parts of the behavior are supposed to be configurable?*
    - time on page / all the time present
    - present on initial page load / present on scroll
    - settings page, if this is a plugin
    - widget settings, maybe, if this could be set as a widget
- Easily-configured styles for this partial

Questions:

- Where did I do previous work on plugin template partials, and how much of that can be copied here?
- How much of this must be custom JS?

**Comment by kaylima** [comment]
[WordPress plugins (public folder)-20170808T214907Z-001.zip](https://github.com/INN/umbrella-rivard-report/files/1210036/WordPress.plugins.public.folder.-20170808T214907Z-001.zip)

**Comment by benlk** [comment]
Things that are in that folder:

- a copy of the VOSD Newsletter List plugin
- a copy of Popup Maker https://wppopupmaker.com/
- a copy of the VOSD Donation plugin, which 

@julia67 was the intent that we should just use Popup Maker, styled appropriately, to do the homepage popup? Triggering the popup on scroll is through an add-on: https://wppopupmaker.com/extensions/scroll-triggered-popups/

The popup plugin is impressively configurable. If we so choose, we can rely on the plugin's built-in theme editor for styles. It supports Gravity Forms, so I'm guessing it supports other shortcodes.

The VOSD Newsletter plugin is written assuming a version of PHP that is newer than what is on the Rivard VM that is set up on my computers; it would be nice to migrate this umbrella repo from the Vagrantfile-based VM the umbrella currently uses to the new Valet-based configuration if we have an hour. 

Neither of the Voice of San Diego plugins are on production.

**Comment by julia67** [comment]
_Background: That zip was provided by the Hub – we can use, modify, or ignore any of it as we see fit._

- Let's definitely use the popup plugin + add-ons if they seem solid.
- Go ahead and update the umbrella repo (be sure to document the new process) if that'll let us use the newsletter plugin.
- **Ignore** the VOSD Donation files for this project....the Rivard donation plugin on production is better.

**Comment by benlk** [comment]
<img width="1037" alt="screen shot 2017-08-11 at 10 50 27 am" src="https://user-images.githubusercontent.com/1754187/29218474-e99cf4f4-7e82-11e7-8f93-e0b5f04ac5ba.png">

The VOSD newsletter plugin's `[newsletter-list]` shortcode is currently tied to the Voice of San Diego's Mailchimp account; we can modify it to fit Rivard by changing the IDs, but they're hardcoded and thus we should not put the plugin into publicly-visible version control:

```php
<?php       
class MailChimpApi {
    // Mailchimp API Ids
    var $apiKey = 'this should definitely not be published';
    var $masterListId = 'some hex digits';
    var $newsletterGroupId = 'an integer';
```

That's in `lib/mailchimp-api-wrapper.php` in the newsletter plugin; I've removed the link to the zip from Kay's comment because it contained the un-sanitized version.

We can also stuff a normal MailChimp form into that signup, with styles. That route will more closely match the Chalkbeat form seen above, and will be more configurable in terms of messaging than the VOSD's signup form plugin, where everything is hardcoded.

Should we go with an updated version of the newsletter subscription list plugin, or just a plain mailchimp form?

Here's the demo URL: http://rrlargo.staging.wpengine.com/

For testing, I recommend just opening that in an incognito window in a browser that doesn't have any other incognito windows; dismissing it sets a cookie that doesn't expire for a year (this is configurable).

**Comment by benlk** [comment]
Questions for them:
- How do they want the popup configured to appear, and where? (This is all configurable through the backend, so we just need a general idea)

- [ ] switch to very simple mailchimp form, from MailChimp's form generator
- [ ] styles for the form
- [ ] remove the VOSD plugin from staging

**Comment by benlk** [comment]
<img width="1057" alt="screen shot 2017-08-15 at 2 01 24 pm" src="https://user-images.githubusercontent.com/1754187/29328947-414c4cb2-81c2-11e7-8c41-e43dbe9ddd19.png">


Staging has been updated with this Mailchimp form code:

```
<div id="mc_embed_signup">
	<form action="//therivardreport.us5.list-manage.com/subscribe/post?u=3845baa9e7672a9eb5e9569d4&amp;id=1576c62124" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
		<h4>Subscribe to our mailing list</h4>
		<div class="mc-field-group input-append">
			<label for="mce-EMAIL" class="visuallyhidden">Email Address</label><input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Email address"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
		</div>
		<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
		<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_3845baa9e7672a9eb5e9569d4_1576c62124" tabindex="-1" value=""></div>
	</form>
	<p><a href="http://us5.campaign-archive1.com/home/?u=3845baa9e7672a9eb5e9569d4&id=1576c62124" title="View previous campaigns">View previous campaigns.</a></p>
</div>
```
The `label` and `input`s are smooshed together because, when they're on their own lines, WordPress inserts a `<br/>` that forces each onto its own line.

This differs from the normal MailChimp code in that it's using `.visuallyhidden` on the label, has a `placeholder="Email address"` on the email address form, and groups the submit button with the email address form using a `.input-append` class from Bootstrap that is included in Largo. Some spare `<div>`s were also removed.

Google's recommendations for popups are here: https://webmasters.googleblog.com/2016/08/helping-users-easily-access-content-on.html

We should think about mobile styles for this popup:

<img width="423" alt="screen shot 2017-08-15 at 2 00 42 pm" src="https://user-images.githubusercontent.com/1754187/29328927-3165df70-81c2-11e7-924c-0851c316bbf3.png">

**Comment by benlk** [comment]
Controls for the popup are found in several places:

- The settings controlling the behavior (when it appears, how it's dismissed, how big it is, where it's placed) of the specific popup are found on the popup's editor page, at Dashboard > Popup Editor > All Popups > edit: http://docs.wppopupmaker.com/article/39-creating-a-popup
- The settings controlling much of the appearance (what it looks like) of the popup are found in the popup theme editor: http://docs.wppopupmaker.com/category/154-theming-popups
- Some CSS stuff is handled through the child theme, in the current staging branch's theme's `less/popmake.less`: https://github.com/INN/umbrella-rivard-report/blob/staging/wp-content/themes/rivard-report/less/popmake.less

**Comment by benlk** [comment]
Deployed in #12, with popup and theme copied from staging.
